import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();

// 按中文名匹配，为每款游戏分配类型标签（标签表：ARPG、RPG、动作、开放世界等游戏类型）
const tagMap = [
  ["Apex Legends", ["射击", "多人", "竞技"]],
  ["彩虹六号:围攻", ["射击", "多人", "竞技"]],
  ["艾尔登法环 黑夜君临", ["ARPG", "动作", "多人", "魂类"]],
  ["ARK: Survival Evolved", ["生存", "开放世界", "多人"]],
  ["PUBG: BATTLEGROUNDS", ["射击", "多人", "生存"]],
  ["Outward", ["ARPG", "开放世界", "生存"]],
  ["遗迹2", ["射击", "ARPG", "多人"]],
  ["幸福工厂", ["模拟", "经营", "开放世界"]],
  ["DARK SOULS III", ["ARPG", "动作", "魂类"]],
  ["艾尔登法环", ["ARPG", "开放世界", "魂类"]],
  ["FINAL FANTASY VII REBIRTH", ["RPG", "动作", "冒险"]],
  ["No Man's Sky", ["生存", "探索", "开放世界", "科幻"]],
  ["DEATH STRANDING 2: ON THE BEACH", ["动作", "冒险", "叙事"]],
  ["极限竞速:地平线6", ["竞速", "开放世界"]],
  ["Warhammer: Vermintide 2", ["动作", "多人", "第一人称"]],
  ["Stellaris", ["策略", "模拟"]],
  ["Wuthering Waves", ["ARPG", "开放世界", "动作"]],
  ["DEATH STRANDING", ["动作", "冒险", "叙事"]],
  ["FINAL FANTASY XV", ["RPG", "动作", "开放世界"]],
  ["The Elder Scrolls IV: Oblivion", ["RPG", "开放世界"]],
  ["巫师3:狂猎", ["RPG", "开放世界", "叙事"]],
  ["The Blood of Dawnwalker", ["ARPG", "冒险", "叙事"]],
  ["The Elder Scrolls V", ["RPG", "开放世界"]],
  ["黑神话:悟空", ["ARPG", "动作"]],
  ["FINAL FANTASY XVI", ["ARPG", "动作"]],
  ["DARK SOULS II", ["ARPG", "动作", "魂类"]],
  ["Dragon's Dogma 2", ["ARPG", "开放世界", "动作"]],
  ["NieR:Automata", ["ARPG", "动作", "叙事"]],
  ["Tom Clancy's The Division", ["射击", "多人", "开放世界"]],
  ["Ghostrunner", ["动作", "第一人称", "独立"]],
  ["Enshrouded", ["生存", "开放世界", "多人", "沙盒"]],
  ["FINAL FANTASY VII REMAKE INTERGRADE", ["ARPG", "动作"]],
  ["明末:渊虚之羽", ["ARPG", "魂类", "动作"]],
  ["Palworld", ["生存", "开放世界", "多人"]],
  ["NieR Replicant", ["ARPG", "动作", "叙事"]],
  ["战地风云 6", ["射击", "多人", "第一人称"]],
  ["Subnautica", ["生存", "探索", "开放世界"]],
  ["Fallout 4", ["RPG", "开放世界", "射击"]],
  ["Dragon's Dogma: Dark Arisen", ["ARPG", "开放世界", "动作"]],
  ["Ghost of Tsushima", ["动作", "开放世界", "潜行"]],
  ["Need for Speed Payback", ["竞速", "动作"]],
  ["放松时光:与你共享Lo-Fi故事", ["休闲", "叙事", "独立"]],
  ["消逝的光芒2", ["生存", "动作", "开放世界"]],
  ["Lords of the Fallen", ["ARPG", "魂类"]],
  ["Control", ["动作", "冒险", "科幻"]],
  ["Dishonored 2", ["潜行", "动作", "冒险"]],
  ["地铁:离乡", ["射击", "生存", "叙事"]],
  ["深海迷航:冰点之下", ["生存", "探索"]],
  ["Far Cry 5", ["射击", "开放世界", "动作"]],
  ["Grand Theft Auto V", ["动作", "开放世界"]],
  ["Wolcen: Lords of Mayhem", ["ARPG", "动作"]],
  ["刺客信条:大革命", ["动作", "潜行", "开放世界"]],
  ["Dying Light", ["生存", "动作", "开放世界"]],
  ["Kingdom Come: Deliverance", ["RPG", "开放世界"]],
  ["战地风云 2042", ["射击", "多人", "第一人称"]],
  ["Assassin's Creed Odyssey", ["RPG", "开放世界", "动作"]],
  ["Xenon Racer", ["竞速"]],
  ["Dishonored: Death of the Outsider", ["潜行", "动作"]],
  ["Outer Wilds", ["探索", "解谜", "独立"]],
  ["Portal Knights", ["动作", "沙盒", "生存"]],
  ["命运2", ["射击", "多人", "动作"]],
  ["Soulmask", ["生存", "开放世界", "多人"]],
  ["尘封大陆", ["ARPG", "动作", "开放世界"]],
  ["Titanfall 2", ["射击", "动作", "第一人称"]],
  ["深海迷航2:异星水域", ["生存", "探索", "多人"]],
  ["Tricolour Lovestory", ["文字冒险", "独立"]],
  ["生化奇兵:无限", ["射击", "叙事", "第一人称"]],
  ["Mortal Shell", ["ARPG", "魂类"]],
  ["Monster Hunter: World", ["动作", "多人"]],
  ["Big Walk", ["冒险", "多人", "休闲"]],
  ["Sid Meier's Civilization VI", ["策略"]],
  ["Danganronpa 2: Goodbye Despair", ["文字冒险", "解谜"]],
  ["ARC Raiders", ["射击", "多人", "生存"]],
  ["心渊梦境", ["平台", "动作", "独立"]],
  ["武士 零", ["动作", "平台", "独立"]],
  ["State of Decay 2", ["生存", "开放世界", "多人"]],
  ["Far Cry 3", ["射击", "开放世界", "动作"]],
  ["Ravenswatch", ["动作", "多人"]],
  ["Mirror", ["解谜", "独立"]],
  ["极限竞速:地平线 4", ["竞速", "开放世界"]],
  ["Hurtworld", ["生存", "多人", "开放世界"]],
  ["HITMAN 2", ["潜行", "动作"]],
  ["全境封锁2", ["射击", "多人", "开放世界"]],
  ["Far Cry 4", ["射击", "开放世界", "动作"]],
  ["呼吸边缘", ["冒险", "独立", "解谜"]],
  ["武装突袭3", ["模拟", "射击", "多人"]],
  ["荣耀战魂", ["动作", "多人", "格斗"]],
  ["GTFO", ["射击", "多人", "恐怖"]],
  ["Mass Effect: Andromeda", ["RPG", "射击", "科幻"]],
  ["Counter-Strike 2", ["射击", "多人", "竞技"]],
  ["猎人:荒野的召唤", ["模拟", "休闲", "探索"]],
  ["Portal 2", ["解谜", "第一人称", "叙事"]],
  ["极限国度", ["竞速", "开放世界", "多人"]],
  ["Avowed", ["RPG", "ARPG", "开放世界"]],
  ["Conan Exiles", ["生存", "多人", "开放世界"]],
  ["光明记忆:无限", ["射击", "动作", "第一人称"]],
  ["Terraria", ["生存", "沙盒", "平台"]],
  ["龙腾世纪审判", ["RPG", "开放世界"]],
  ["Middle-earth: Shadow of War", ["动作", "开放世界"]],
  ["Salt and Sanctuary", ["ARPG", "平台", "魂类"]],
  ["Sherlock Holmes: The Devil's Daughter", ["解谜", "冒险"]],
  ["Hellblade: Senua's Sacrifice", ["动作", "叙事"]],
  ["Saints Row IV", ["动作", "开放世界"]],
  ["Steelrising", ["ARPG", "魂类", "动作"]],
  ["RWBY: Grimm Eclipse", ["动作", "多人"]],
  ["ABZÛ", ["冒险", "探索", "休闲"]],
  ["Human Fall Flat", ["休闲", "多人", "解谜"]],
  ["Devil May Cry 5", ["动作", "格斗"]],
  ["Mad Max", ["动作", "开放世界"]],
  ["Cities: Skylines", ["模拟", "经营"]],
  ["Horizon Zero Dawn", ["ARPG", "开放世界", "科幻"]],
  ["高考恋爱一百天", ["文字冒险", "独立"]],
  ["Dishonored", ["潜行", "动作", "冒险"]],
  ["Assassin's Creed III", ["动作", "潜行", "开放世界"]],
  ["Battlefield 1", ["射击", "多人", "第一人称"]],
  ["仁王2", ["ARPG", "动作", "魂类"]],
  ["光明记忆", ["射击", "动作", "第一人称"]],
  ["Starfield", ["RPG", "开放世界", "科幻"]],
];

let updated = 0;
const missing = [];

for (const [nameZh, tags] of tagMap) {
  const g = await p.game.findUnique({ where: { nameZh } });
  if (!g) {
    missing.push(nameZh);
    continue;
  }
  await p.game.update({ where: { id: g.id }, data: { tags: JSON.stringify(tags) } });
  updated++;
}

console.log(`已为 ${updated} 款游戏写入标签`);
if (missing.length) {
  console.log("未匹配到的游戏：", missing.join("、"));
}
await p.$disconnect();