import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();

// nameZh: 中文名；nameEn: 英文名。
// 规则：保留正题名（含序号），去掉版本/发行版标记与 ™；无官方中文名的纯英文游戏，中文栏沿用英文名。
// nameEn 为空或与 nameZh 相同表示无独立英文名（英文模式将回退显示中文名）。
const data = [
  ["Apex Legends", "Apex Legends"],
  ["彩虹六号:围攻", "Tom Clancy's Rainbow Six Siege"],
  ["艾尔登法环 黑夜君临", "Elden Ring Nightreign"],
  ["ARK: Survival Evolved", "ARK: Survival Evolved"],
  ["PUBG: BATTLEGROUNDS", "PUBG: BATTLEGROUNDS"],
  ["Outward", "Outward"],
  ["遗迹2", "Remnant 2"],
  ["幸福工厂", "Satisfactory"],
  ["DARK SOULS III", "DARK SOULS III"],
  ["艾尔登法环", "Elden Ring"],
  ["FINAL FANTASY VII REBIRTH", "FINAL FANTASY VII REBIRTH"],
  ["No Man's Sky", "No Man's Sky"],
  ["DEATH STRANDING 2: ON THE BEACH", "DEATH STRANDING 2: ON THE BEACH"],
  ["极限竞速:地平线6", "Forza Horizon 6"],
  ["Warhammer: Vermintide 2", "Warhammer: Vermintide 2"],
  ["Stellaris", "Stellaris"],
  ["Wuthering Waves", "Wuthering Waves"],
  ["DEATH STRANDING", "DEATH STRANDING"],
  ["FINAL FANTASY XV", "FINAL FANTASY XV"],
  ["The Elder Scrolls IV: Oblivion", "The Elder Scrolls IV: Oblivion"],
  ["巫师3:狂猎", "The Witcher 3: Wild Hunt"],
  ["The Blood of Dawnwalker", "The Blood of Dawnwalker"],
  ["The Elder Scrolls V", "The Elder Scrolls V"],
  ["黑神话:悟空", "Black Myth: Wukong"],
  ["FINAL FANTASY XVI", "FINAL FANTASY XVI"],
  ["DARK SOULS II", "DARK SOULS II"],
  ["Dragon's Dogma 2", "Dragon's Dogma 2"],
  ["NieR:Automata", "NieR:Automata"],
  ["Tom Clancy's The Division", "Tom Clancy's The Division"],
  ["Ghostrunner", "Ghostrunner"],
  ["Enshrouded", "Enshrouded"],
  ["FINAL FANTASY VII REMAKE INTERGRADE", "FINAL FANTASY VII REMAKE INTERGRADE"],
  ["明末:渊虚之羽", "Wuchang: Fallen Feathers"],
  ["Palworld", "Palworld"],
  ["NieR Replicant", "NieR Replicant"],
  ["战地风云 6", "Battlefield 6"],
  ["Subnautica", "Subnautica"],
  ["Fallout 4", "Fallout 4"],
  ["Dragon's Dogma: Dark Arisen", "Dragon's Dogma: Dark Arisen"],
  ["Ghost of Tsushima", "Ghost of Tsushima"],
  ["Need for Speed Payback", "Need for Speed Payback"],
  ["放松时光:与你共享Lo-Fi故事", ""],
  ["消逝的光芒2", "Dying Light 2"],
  ["Lords of the Fallen", "Lords of the Fallen"],
  ["Control", "Control"],
  ["Dishonored 2", "Dishonored 2"],
  ["地铁:离乡", "Metro Exodus"],
  ["深海迷航:冰点之下", "Subnautica: Below Zero"],
  ["Far Cry 5", "Far Cry 5"],
  ["Grand Theft Auto V", "Grand Theft Auto V"],
  ["Wolcen: Lords of Mayhem", "Wolcen: Lords of Mayhem"],
  ["刺客信条:大革命", "Assassin's Creed Unity"],
  ["Dying Light", "Dying Light"],
  ["Kingdom Come: Deliverance", "Kingdom Come: Deliverance"],
  ["战地风云 2042", "Battlefield 2042"],
  ["Assassin's Creed Odyssey", "Assassin's Creed Odyssey"],
  ["Xenon Racer", "Xenon Racer"],
  ["Dishonored: Death of the Outsider", "Dishonored: Death of the Outsider"],
  ["Outer Wilds", "Outer Wilds"],
  ["Portal Knights", "Portal Knights"],
  ["命运2", "Destiny 2"],
  ["Soulmask", "Soulmask"],
  ["尘封大陆", "Atlas Fallen"],
  ["Titanfall 2", "Titanfall 2"],
  ["深海迷航2:异星水域", "Subnautica 2"],
  ["Tricolour Lovestory", "Tricolour Lovestory"],
  ["生化奇兵:无限", "Bioshock Infinite"],
  ["Mortal Shell", "Mortal Shell"],
  ["Monster Hunter: World", "Monster Hunter: World"],
  ["Big Walk", "Big Walk"],
  ["Sid Meier's Civilization VI", "Sid Meier's Civilization VI"],
  ["Danganronpa 2: Goodbye Despair", "Danganronpa 2: Goodbye Despair"],
  ["ARC Raiders", "ARC Raiders"],
  ["心渊梦境", "AfterImage"],
  ["武士 零", "Katana ZERO"],
  ["State of Decay 2", "State of Decay 2"],
  ["Far Cry 3", "Far Cry 3"],
  ["Ravenswatch", "Ravenswatch"],
  ["Mirror", "Mirror"],
  ["极限竞速:地平线 4", "Forza Horizon 4"],
  ["Hurtworld", "Hurtworld"],
  ["HITMAN 2", "HITMAN 2"],
  ["全境封锁2", "The Division 2"],
  ["Far Cry 4", "Far Cry 4"],
  ["呼吸边缘", "Breathedge"],
  ["武装突袭3", "Arma 3"],
  ["荣耀战魂", "For Honor"],
  ["GTFO", "GTFO"],
  ["Mass Effect: Andromeda", "Mass Effect: Andromeda"],
  ["Counter-Strike 2", "Counter-Strike 2"],
  ["猎人:荒野的召唤", "theHunter: Call of the Wild"],
  ["Portal 2", "Portal 2"],
  ["极限国度", "Riders Republic"],
  ["Avowed", "Avowed"],
  ["Conan Exiles", "Conan Exiles"],
  ["光明记忆:无限", "Bright Memory: Infinite"],
  ["Terraria", "Terraria"],
  ["龙腾世纪审判", "Dragon Age: Inquisition"],
  ["Middle-earth: Shadow of War", "Middle-earth: Shadow of War"],
  ["Salt and Sanctuary", "Salt and Sanctuary"],
  ["Sherlock Holmes: The Devil's Daughter", "Sherlock Holmes: The Devil's Daughter"],
  ["Hellblade: Senua's Sacrifice", "Hellblade: Senua's Sacrifice"],
  ["Saints Row IV", "Saints Row IV"],
  ["Steelrising", "Steelrising"],
  ["RWBY: Grimm Eclipse", "RWBY: Grimm Eclipse"],
  ["ABZÛ", "ABZÛ"],
  ["Human Fall Flat", "Human Fall Flat"],
  ["Devil May Cry 5", "Devil May Cry 5"],
  ["Mad Max", "Mad Max"],
  ["Cities: Skylines", "Cities: Skylines"],
  ["Horizon Zero Dawn", "Horizon Zero Dawn"],
  ["高考恋爱一百天", "Gaokao.Love.100Days"],
  ["Dishonored", "Dishonored"],
  ["Assassin's Creed III", "Assassin's Creed III"],
  ["Battlefield 1", "Battlefield 1"],
  ["仁王2", "Nioh 2"],
  ["光明记忆", "Bright Memory"],
  ["Starfield", "Starfield"],
];

let created = 0;
let skipped = 0;
for (const [nameZh, nameEn] of data) {
  const zh = nameZh.trim().replace(/[\u200b\u202f\u00a0]/g, " ").trim();
  const exists = await p.game.findUnique({ where: { nameZh: zh } });
  if (exists) {
    skipped++;
    console.log(`跳过(已存在): ${zh}`);
    continue;
  }
  await p.game.create({
    data: {
      nameZh: zh,
      nameEn: (nameEn || zh).trim(),
      description: "",
    },
  });
  created++;
}
console.log(`共写入 ${created} 款，跳过 ${skipped} 款。库中现有 ${await p.game.count()} 款。`);
await p.$disconnect();