// 常见游戏标签中英对照（zh → en）；英文页显示英文、中文页显示中文
const ZH2EN = {
  动作: "Action",
  动作类: "Action",
  冒险: "Adventure",
  冒险类: "Adventure",
  动作冒险: "Action-Adventure",
  角色扮演: "RPG",
  角色扮演类: "RPG",
  角色扮演游戏: "RPG",
  动作角色扮演: "Action RPG",
  ARPG: "Action RPG",
  射击: "Shooter",
  射击类: "Shooter",
  第一人称射击: "FPS",
  FPS: "FPS",
  第三人称射击: "TPS",
  TPS: "TPS",
  策略: "Strategy",
  策略类: "Strategy",
  即时战略: "RTS",
  RTS: "RTS",
  回合制策略: "Turn-Based Strategy",
  模拟: "Simulation",
  模拟类: "Simulation",
  模拟经营: "Management",
  经营: "Management",
  模拟飞行: "Flight Sim",
  体育: "Sports",
  体育竞技: "Sports",
  竞速: "Racing",
  赛车: "Racing",
  解谜: "Puzzle",
  益智解谜: "Puzzle",
  益智: "Puzzle",
  恐怖: "Horror",
  恐怖类: "Horror",
  生存: "Survival",
  生存类: "Survival",
  生存恐怖: "Survival Horror",
  休闲: "Casual",
  休闲类: "Casual",
  独立: "Indie",
  独立游戏: "Indie",
  像素: "Pixel",
  像素风: "Pixel Art",
  像素风格: "Pixel Art",
  开放世界: "Open World",
  开放世界类: "Open World",
  沙盒: "Sandbox",
  沙盒类: "Sandbox",
  建造: "Building",
  建造类: "Building",
  合作: "Co-op",
  合作类: "Co-op",
  多人: "Multiplayer",
  联机: "Multiplayer",
  在线多人: "Online Multiplayer",
  本地多人: "Local Multiplayer",
  本地合作: "Local Co-op",
  竞技: "Competitive",
  对战: "PvP",
  PvP: "PvP",
  单人: "Singleplayer",
  单机: "Singleplayer",
  角色: "Character",
  Roguelike: "Roguelike",
  Roguelite: "Roguelite",
  肉鸽: "Roguelike",
  卡牌: "Card",
  卡牌类: "Card Game",
  桌游: "Board Game",
  格斗: "Fighting",
  格斗类: "Fighting",
  平台跳跃: "Platformer",
  横版过关: "Platformer",
  类魂: "Souls-like",
  魂类: "Souls-like",
  音乐: "Rhythm",
  音游: "Rhythm",
  视觉小说: "Visual Novel",
  文字冒险: "Visual Novel",
  科幻: "Sci-Fi",
  奇幻: "Fantasy",
  魔幻: "Fantasy",
  中世纪: "Medieval",
  后末日: "Post-apocalyptic",
  末日: "Post-apocalyptic",
  赛博朋克: "Cyberpunk",
  历史: "Historical",
  二战: "WWII",
  战争: "War",
  军事: "Military",
  太空: "Space",
  探索: "Exploration",
  收集: "Collectathon",
  收集类: "Collectathon",
  剧情: "Story",
  剧情丰富: "Story-Rich",
  潜行: "Stealth",
  叙事: "Narrative",
  第一人称: "First Person",
  平台: "Platform",
  驾驶: "Driving",
  狩猎: "Hunting",
  种田: "Farming",
  烹饪: "Cooking",
  策略模拟: "Grand Strategy",
  银河恶魔城: "Metroidvania",
  类银河恶魔城: "Metroidvania",
  刷宝: "Looter",
  刷子: "Looter",
  弹幕: "Bullet Hell",
  塔防: "Tower Defense",
  地牢: "Dungeon",
  探索类: "Exploration",
  免费: "Free-to-Play",
  免费游玩: "Free-to-Play",
  付费: "Premium",
  跨平台: "Cross-platform",
  女性主角: "Female Protagonist",
  可爱: "Cute",
  治愈: "Wholesome",
  黑暗: "Dark",
  黑暗风: "Dark",
};

const EN2ZH = Object.fromEntries(
  Object.entries(ZH2EN).map(([zh, en]) => [en.toLowerCase(), zh])
);

// 按当前语言翻译标签；找不到对应翻译时原样返回（标签为自由文本，容忍个别缺失）
export function translateTag(tag, isEn) {
  if (!tag) return tag;
  return isEn ? ZH2EN[tag] ?? tag : EN2ZH[String(tag).toLowerCase()] ?? tag;
}